<?php

namespace Database\Seeders;

use App\Models\BetMarket;
use App\Models\Bookmaker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookmakerSeeder extends Seeder
{
    public function run(): void
    {
        $bookmakers = [
            [
                'name'            => 'Bet9ja',
                'slug'            => 'bet9ja',
                'affiliate_url'   => 'https://bet9ja.com',
                'welcome_offer'   => '100% Welcome Bonus up to ₦100,000',
                'bonus_text'      => '100% up to ₦100k',
                'rating'          => 9.2,
                'sort_order'      => 1,
                'is_featured'     => true,
                'fast_withdrawal' => true,
                'min_deposit'     => '₦100',
                'withdrawal_time' => 'Instant',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2013,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=bet9ja.com&sz=64',
                'key_features'    => ['Widest market coverage', 'Instant withdrawals', 'NPFL & local leagues', 'Mobile app'],
                'review'          => "Bet9ja is Nigeria's leading sportsbook, offering one of the widest selections of football markets in the country. With fast payouts, a robust mobile app, and exclusive Nigerian league coverage, it remains the top choice for Nigerian bettors.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'over-under-1-5', 'double-chance', 'correct-score', 'asian-handicap', 'anytime-scorer', 'total-corners'],
            ],
            [
                'name'            => 'SportyBet',
                'slug'            => 'sportybet',
                'affiliate_url'   => 'https://sportybet.com',
                'welcome_offer'   => '100% First Deposit Bonus up to ₦50,000',
                'bonus_text'      => '100% up to ₦50k',
                'rating'          => 8.9,
                'sort_order'      => 2,
                'is_featured'     => true,
                'fast_withdrawal' => true,
                'min_deposit'     => '₦50',
                'withdrawal_time' => '< 1 hour',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2018,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=sportybet.com&sz=64',
                'key_features'    => ['Highest odds on football', 'Fast withdrawals', 'Jackpot games', 'Top mobile UX'],
                'review'          => "SportyBet has rapidly grown to become one of the most popular betting platforms in Nigeria. Known for its user-friendly interface, high odds on football, and quick withdrawals.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'over-under-1-5', 'double-chance', 'draw-no-bet', 'asian-handicap', 'first-scorer'],
            ],
            [
                'name'            => 'BetKing',
                'slug'            => 'betking',
                'affiliate_url'   => 'https://betking.com',
                'welcome_offer'   => '100% Welcome Bonus up to ₦50,000',
                'bonus_text'      => '100% up to ₦50k',
                'rating'          => 8.6,
                'sort_order'      => 3,
                'is_featured'     => true,
                'fast_withdrawal' => true,
                'min_deposit'     => '₦100',
                'withdrawal_time' => '< 2 hours',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2018,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=betking.com&sz=64',
                'key_features'    => ['Competitive odds', 'Local league coverage', 'Easy-to-use app', 'Weekly promos'],
                'review'          => "BetKing is a fast-growing Nigerian bookmaker offering competitive odds across a wide range of football leagues. Features an easy-to-use platform and attractive promotions.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'double-chance', 'correct-score', 'first-team-score'],
            ],
            [
                'name'            => 'NairaBet',
                'slug'            => 'nairabet',
                'affiliate_url'   => 'https://nairabet.com',
                'welcome_offer'   => '10% Welcome Bonus up to ₦250,000',
                'bonus_text'      => '10% up to ₦250k',
                'rating'          => 8.3,
                'sort_order'      => 4,
                'is_featured'     => false,
                'fast_withdrawal' => false,
                'min_deposit'     => '₦200',
                'withdrawal_time' => '1-3 days',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2009,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=nairabet.com&sz=64',
                'key_features'    => ['Pioneer in Nigeria', 'Large bonus cap', 'Veteran platform', 'Casino games'],
                'review'          => "NairaBet was one of the first online sportsbooks in Nigeria and continues to offer a solid product. Trusted by millions of Nigerian bettors since 2009.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'over-under-1-5', 'double-chance', 'ht-result', 'ht-ft'],
            ],
            [
                'name'            => 'MerryBet',
                'slug'            => 'merrybet',
                'affiliate_url'   => 'https://merrybet.com',
                'welcome_offer'   => '50% Welcome Bonus up to ₦50,000',
                'bonus_text'      => '50% up to ₦50k',
                'rating'          => 8.1,
                'sort_order'      => 5,
                'is_featured'     => false,
                'fast_withdrawal' => false,
                'min_deposit'     => '₦200',
                'withdrawal_time' => '1-2 days',
                'live_betting'    => false,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2013,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=merrybet.com&sz=64',
                'key_features'    => ['Virtual sports', 'Pool betting', 'Good customer support', 'Simple interface'],
                'review'          => "MerryBet is a well-established Nigerian bookmaker with a focus on football and virtual sports. Offers competitive odds and a straightforward betting experience.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'double-chance', 'draw-no-bet'],
            ],
            [
                'name'            => '1xBet',
                'slug'            => '1xbet',
                'affiliate_url'   => 'https://1xbet.com',
                'welcome_offer'   => '200% First Deposit Bonus up to ₦130,000',
                'bonus_text'      => '200% up to ₦130k',
                'rating'          => 8.7,
                'sort_order'      => 6,
                'is_featured'     => false,
                'fast_withdrawal' => true,
                'min_deposit'     => '₦360',
                'withdrawal_time' => '< 24 hours',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'Curacao',
                'founded_year'    => 2007,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=1xbet.com&sz=64',
                'key_features'    => ['1000+ markets per game', 'Live streaming', 'Exotic bet types', 'Huge bonus'],
                'review'          => "1xBet is an internationally renowned bookmaker with one of the largest selections of betting markets available in Nigeria. Ideal for bettors who want exotic markets and live betting.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'over-under-3-5', 'over-under-1-5', 'asian-handicap', 'euro-handicap', 'correct-score', 'anytime-scorer', 'first-scorer', 'total-corners', 'total-cards', 'ht-ft', 'win-to-nil', 'clean-sheet'],
            ],
            [
                'name'            => 'Betway',
                'slug'            => 'betway',
                'affiliate_url'   => 'https://betway.com.ng',
                'welcome_offer'   => '50% Welcome Bonus up to ₦100,000',
                'bonus_text'      => '50% up to ₦100k',
                'rating'          => 8.5,
                'sort_order'      => 7,
                'is_featured'     => false,
                'fast_withdrawal' => true,
                'min_deposit'     => '₦500',
                'withdrawal_time' => '< 24 hours',
                'live_betting'    => true,
                'mobile_app'      => true,
                'license'         => 'NLRC',
                'founded_year'    => 2016,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=betway.com.ng&sz=64',
                'key_features'    => ['Global brand', 'Live streaming', 'Champions League coverage', 'Trusted payouts'],
                'review'          => "Betway is a globally trusted bookmaker with a strong presence in Nigeria. Offers an excellent mobile app, live streaming, and competitive odds on top European leagues.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'over-under-1-5', 'double-chance', 'draw-no-bet', 'asian-handicap', 'anytime-scorer', 'total-corners'],
            ],
            [
                'name'            => 'BangBet',
                'slug'            => 'bangbet',
                'affiliate_url'   => 'https://bangbet.com',
                'welcome_offer'   => '100% Welcome Bonus up to ₦50,000',
                'bonus_text'      => '100% up to ₦50k',
                'rating'          => 7.9,
                'sort_order'      => 8,
                'is_featured'     => false,
                'fast_withdrawal' => false,
                'min_deposit'     => '₦200',
                'withdrawal_time' => '1-3 days',
                'live_betting'    => true,
                'mobile_app'      => false,
                'license'         => 'NLRC',
                'founded_year'    => 2020,
                'logo_url'        => 'https://www.google.com/s2/favicons?domain=bangbet.com&sz=64',
                'key_features'    => ['Local promos', 'Football focus', 'Referral bonuses', 'Simple interface'],
                'review'          => "BangBet is a growing Nigerian sportsbook with attractive bonuses and a focus on football. Popular among Nigerian bettors for its local promotions and quick payments.",
                'markets'         => ['1x2', 'btts', 'over-under-2-5', 'double-chance', 'first-team-score'],
            ],
        ];

        foreach ($bookmakers as $data) {
            $marketSlugs = $data['markets'];
            unset($data['markets']);

            $bm = Bookmaker::updateOrCreate(['slug' => $data['slug']], array_merge($data, ['is_active' => true]));

            $marketIds = BetMarket::whereIn('slug', $marketSlugs)->pluck('id');
            $bm->betMarkets()->sync($marketIds);
        }
    }
}
