<x-app-layout>
<x-slot name="title">Editorial Policy — {{ config('app.name') }}</x-slot>
<x-slot name="description">Read the {{ config('app.name') }} editorial policy — how we generate tips, our independence standards, and how affiliate relationships are managed.</x-slot>

<div style="max-width:860px;margin:0 auto;padding:2rem 2rem">

    <div style="font-size:.75rem;color:var(--muted);margin-bottom:1.5rem">
        <a href="{{ route('home') }}" style="color:var(--muted);text-decoration:none">Home</a>
        <span style="margin:0 .4rem">›</span>
        <span style="color:var(--text)">Editorial Policy</span>
    </div>

    <h1 style="font-family:var(--fh);font-size:2.2rem;letter-spacing:.08em;color:var(--text);margin-bottom:.5rem">Editorial Policy</h1>
    <p style="font-size:.82rem;color:var(--muted);margin-bottom:2rem">Last updated: {{ \Carbon\Carbon::now()->format('d F Y') }}</p>

    <div style="display:grid;gap:1.25rem">

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">1. Independence of Tips</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                All betting tips published on {{ config('app.name') }} are generated by our AI analysis pipeline and reviewed by our editorial team. Commercial relationships with bookmakers — including affiliate agreements — have <strong style="color:var(--text)">no influence whatsoever</strong> on which tips we publish, which selections we recommend, or which markets we cover. Our tip generation process is entirely separate from our commercial operations.
            </p>
        </div>

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">2. Affiliate Relationships</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0 0 .75rem">
                We list bookmakers on this site and may receive a commission when you register through our links. This commission comes from the bookmaker — it is never added to your costs or deducted from your winnings. We are transparent about this on every bookmakers page.
            </p>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                Bookmakers are ranked on our comparison pages based on an objective scoring rubric that considers: odds quality, market breadth, withdrawal speed, minimum deposit, app quality, licensing, and user trust. Affiliate commission rates are <strong style="color:var(--text)">not a ranking factor</strong>.
            </p>
        </div>

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">3. Accuracy &amp; Corrections</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                We strive for accuracy in all published content. Where an error is identified — whether in a tip, odds figure, or factual claim — we will correct it promptly. Corrections are noted in the relevant article. We do not remove or alter published tips retroactively for the purposes of inflating our track record.
            </p>
        </div>

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">4. AI-Generated Content</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                Tips and match analysis on {{ config('app.name') }} are generated with the assistance of large language models and statistical models. All AI output is reviewed by a human editor before publication. AI-generated tips are clearly labelled on the platform. We are committed to responsible and transparent use of AI in our editorial workflow.
            </p>
        </div>

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">5. No Guaranteed Returns</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                Nothing on this site constitutes financial advice. Betting involves risk and you may lose money. Our tips represent statistical analysis, not guarantees. Past performance of our predictions is not indicative of future results.
            </p>
        </div>

        <div style="background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1.5rem">
            <h2 style="font-family:var(--fh);font-size:1.1rem;letter-spacing:.06em;color:var(--accent);margin-bottom:.75rem">6. Contact</h2>
            <p style="font-size:.87rem;color:var(--muted);line-height:1.9;margin:0">
                If you have a concern about any content published on {{ config('app.name') }}, please contact our editorial team. We take all feedback seriously and aim to respond within 5 business days.
            </p>
        </div>

    </div>

</div>

<x-slot name="footer">@include('layouts.partials.footer')</x-slot>
</x-app-layout>
